/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CalendarioApertura {
  abre_domingo: boolean;
  abre_jueves: boolean;
  abre_lunes: boolean;
  abre_martes: boolean;
  abre_miercoles: boolean;
  abre_sabado: boolean;
  abre_viernes: boolean;
  creada_en: Generated<Timestamp>;
  creada_por: number;
  id: Generated<number>;
  vigente_desde: Timestamp;
}

export interface CalendarioAperturaExcepcion {
  abierto: boolean;
  calendario_id: number;
  fecha: Timestamp;
}

export interface ConfiguracionCostos {
  costos_indirectos_mensuales: number;
  creada_en: Generated<Timestamp>;
  creada_por: number;
  id: Generated<number>;
  pct_comision: number;
  pct_igv: number;
  pct_merma: number;
  salario_administrativo: number;
  salario_cocina: number;
  vigente_desde: Timestamp;
}

export interface ConfiguracionOperativa {
  fila_unica: Generated<boolean>;
  inactividad_sesion_min: number;
  umbral_demora_min: number;
}

export interface SchemaMigrations {
  aplicada_en: Generated<Timestamp>;
  nombre: string;
}

export interface DB {
  calendario_apertura: CalendarioApertura;
  calendario_apertura_excepcion: CalendarioAperturaExcepcion;
  configuracion_costos: ConfiguracionCostos;
  configuracion_operativa: ConfiguracionOperativa;
  schema_migrations: SchemaMigrations;
}
