/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BloqueoAcceso {
  ancla: string;
  bloqueado_hasta: Timestamp | null;
  bloqueos_consecutivos: number;
  fallos_consecutivos: number;
  ultimo_fallo_en: Timestamp;
  valor_ancla: string;
}

export interface CalendarioApertura {
  abre_domingo: boolean;
  abre_jueves: boolean;
  abre_lunes: boolean;
  abre_martes: boolean;
  abre_miercoles: boolean;
  abre_sabado: boolean;
  abre_viernes: boolean;
  creada_en: Generated<Timestamp>;
  creada_por: number;
  id: Generated<number>;
  vigente_desde: Timestamp;
}

export interface CalendarioAperturaExcepcion {
  abierto: boolean;
  calendario_id: number;
  fecha: Timestamp;
}

export interface ConfiguracionCostos {
  costos_indirectos_mensuales: number;
  creada_en: Generated<Timestamp>;
  creada_por: number;
  id: Generated<number>;
  pct_comision: number;
  pct_igv: number;
  pct_merma: number;
  salario_administrativo: number;
  salario_cocina: number;
  vigente_desde: Timestamp;
}

export interface ConfiguracionOperativa {
  fila_unica: Generated<boolean>;
  inactividad_sesion_min: number;
  umbral_demora_min: number;
}

export interface Dispositivo {
  enrolado_en: Generated<Timestamp>;
  expira_en: Timestamp;
  id: Generated<number>;
  nombre: string;
  revocado_en: Timestamp | null;
  rol: string;
  rotado_en: Timestamp | null;
  token_hash: Buffer;
  token_sal: Buffer;
}

export interface Persona {
  activo: boolean;
  contrasena_hash: string | null;
  creada_en: Generated<Timestamp>;
  debe_rotar_contrasena: boolean;
  id: Generated<number>;
  nombre: string;
  rol: string;
  usuario: string | null;
}

export interface SchemaMigrations {
  aplicada_en: Generated<Timestamp>;
  nombre: string;
}

export interface SesionAdmin {
  creada_en: Generated<Timestamp>;
  id: string;
  persona_id: number;
  revocada_en: Timestamp | null;
  token_hash: Buffer;
  token_sal: Buffer;
  ultima_actividad_en: Generated<Timestamp>;
}

export interface DB {
  bloqueo_acceso: BloqueoAcceso;
  calendario_apertura: CalendarioApertura;
  calendario_apertura_excepcion: CalendarioAperturaExcepcion;
  configuracion_costos: ConfiguracionCostos;
  configuracion_operativa: ConfiguracionOperativa;
  dispositivo: Dispositivo;
  persona: Persona;
  schema_migrations: SchemaMigrations;
  sesion_admin: SesionAdmin;
}
